### ISSUE TITLE
Kudometer overlay close button scrolls out of view on mobile

### ISSUE THREAD

**Issue by pascalw** [kabisa/kudo-o-matic#125]
![kudo-meter](https://cloud.githubusercontent.com/assets/304603/26618894/5e16f292-45dc-11e7-841c-de4746598d6c.gif)

Notice the close button scrolling out of view. Also the page is scrolling below the overlay which is pretty distracting.

**Comment by ariejan** [comment]
Closing this in favour of using the mobile app ;)
