### ISSUE TITLE
Crash when filling in a long text about why I am giving kudos

### ISSUE THREAD

**Issue by eirvandelden** [kabisa/kudo-o-matic#13]
_What I did_ Fill in kudos with:
Etienne / Ralph Rooding / 1 / helping with uninstalling Citrix which comes with a damaged uninstaller

_What I got_ "Oops, something went wrong"
_What I expected_ 1 kudo

**Comment by pascalw** [comment]
This is due to [this](https://github.com/kabisa/kudo-o-matic/blob/master/db/migrate/20160330090450_create_activities.rb#L4).

I think we should just change this to a `text` column. @ariejan any reason specifically why this is a `varchar(60)` now?

**Comment by ariejan** [comment]
The original idea was to keep the activity short so 1) it fits on the dashboard and 2) it fits in a tweet. But if more characters are needed, let's just add 'em. 

varchar(255) seems good to me.

**Comment by thnukid** [comment]
Or we put a `<input maxlength="60">` on it?

**Comment by ariejan** [comment]
@CanolKabisa this might be a nice bug to look into to get acquainted with the app a bit.
