### ISSUE TITLE
(Re)design "Giving kudos"

### ISSUE THREAD

**Issue by remcohh** [kabisa/kudo-o-matic#21]
As a user
I want to easily (with minimal effort) give feedback / kudos to others
So that giving kudos is an enjoyable task

**Comment by ariejan** [comment]
Notes/ideas from @CanolKabisa:

 * Adding (optional) comments when giving kudo's 
 * Kudo receiver selection screen with user photo's

**Comment by ariejan** [comment]
Closing this in favour of specific stories/issues to improve the form.
