### ISSUE TITLE
Bugreport: Kudo msgs in Slack no longer display how many Kudos left for the next goal

### ISSUE THREAD

**Issue by Reinoptland** [kabisa/kudo-o-matic#272]
![screen shot 2017-12-05 at 08 10 22](https://user-images.githubusercontent.com/20372832/33594422-06f4f382-d994-11e7-98f4-44beea35bd93.png)

**Comment by Laugslander** [comment]
Thanks for reporting!

This bug is fixed on the develop branch.

**Comment by Reinoptland** [comment]
👍  Nice work!
