### ISSUE TITLE
"Given" Kudo counter does not count +1 Kudos

### ISSUE THREAD

**Issue by martijnversluis** [kabisa/kudo-o-matic#298]
When I like a Kudo transaction in Slack, my "Given" Kudo counter does not increment.

**Comment by Laugslander** [comment]
The `Given` and `Received` counters display the number of `Transactions`, not the number of `Kudos`. Maybe the label should be changed to make this clear.

**Comment by ariejan** [comment]
@martijnversluis the statistics are used to encourage participation - not a race to get as many kudos as possible. E.g. the situation where a user gives 5 kudos three times is preferred over a user giving 20 kudos once. 

I agree with @Laugslander that the labelling should be more clear here. 

Any suggestions?
