### ISSUE TITLE
Scrolling to the bottom of the ₭udometer not possible

### ISSUE THREAD

**Issue by Vreijsen** [kabisa/kudo-o-matic#483]
**Description**
When opening the homepage (https://kudos-o-matic.netlify.com/#/) after login, on a default mac sized screen, it appears that I can not scroll down the ₭udometer. Probably due to it's fixed position.

**To Reproduce**
1. Go to https://kudos-o-matic.netlify.com/#/ on a mac without an external screen attached.
2. Login.
3. Click 'Choose' Kabisa team.
4. Try to scroll down to the origin of the ₭udometer.

**Expected behavior**
The expectation was that I could scroll down the page, rather then the feed so that i could see the beginning of the ₭udometer.

**Screenshots**
<img width="1440" alt="screenshot 2018-12-12 at 14 48 05" src="https://user-images.githubusercontent.com/5426621/49873761-f6ebfb80-fe1c-11e8-88d8-2d18f4954410.png">

**Desktop:**
 - OS: MacOS Mojave, 10.14 (18A391)
 - Browser: Chrome (70.0.3538.110)

**Comment by egonm12** [comment]
Fixed
