### ISSUE TITLE
View transactions table does not fit the wrapper

### ISSUE THREAD

**Issue by thnukid** [kabisa/kudo-o-matic#486]
**Describe the bug**
Table does not fit in the wrapper

**To Reproduce**
1. Go to https://kudos.kabisa.io/account/view_data/transactions
2. Table does not fit in the wrapper container

**Expected behavior**
Does not break the layout

**Screenshots**
<img width="851" alt="screenshot 2018-12-20 at 10 55 38" src="https://user-images.githubusercontent.com/1724804/50277888-ebfd2080-0445-11e9-925e-daf5650c6fbc.png">

**Desktop (please complete the following information):**
- Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
- not tested

**Additional context**

**Comment by ariejan** [comment]
@thnukid thanks for your report. This is part of the current Kudos-o-matic app that will be sunset somewhere in January in favour of the restructured and redesigned app. As this is not a critical issue, we won't fix this and focus on the release of the new version. Thanks!

/cc @egonm12
