### ISSUE TITLE
Add (versions) changelog

### ISSUE THREAD

**Issue by thnukid** [kabisa/kudo-o-matic#504]
**Is your feature request related to a problem? Please describe.**
I want to see the updates and what has changed in the different version of kudomatic, so that I can follow the progress.

**Describe the solution you'd like**
https://keepachangelog.com/en/1.0.0/

**Comment by egonm12** [comment]
Hi @thnukid, thanks for pointing this out. You already noticed me about this a while ago but I haven't updated it yet. Going to do that right away 👍

**Comment by egonm12** [comment]
@thnukid updated (https://github.com/kabisa/kudo-o-matic/blob/develop/CHANGELOG.md). When the readme is updated as well I will make sure it is linked to the changelog.

**Comment by thnukid** [comment]
Awesome!

Would be nice to have a link in the actual app to the Changelog, so that I do not need to go to github for that.

**Comment by egonm12** [comment]
@thnukid added it to the backlog
