### ISSUE TITLE
Webhooks / Slack notifications

### ISSUE THREAD

**Issue by ariejan** [kabisa/kudo-o-matic#6]
As a user
I want to be notified through webhooks / on slack about new activity
So I can stay up to date with activity without having to go to the website.

**Comment by egonm12** [comment]
As a user
I want to get a mention in Slack if someone gave kudo's to me

As a user
I want to see how much kudo's are left until we reach our next goal in Slack

As a user
I want to get a Slack notification if we have reached our next goal

As a user
I want a link in the Slack message to the kudo's website
