### ISSUE TITLE
Autocomplete (and therefore assigning kudos to a specific person) doesn't work in Firefox

### ISSUE THREAD

**Issue by koenkivits** [kabisa/kudo-o-matic#80]
## Reproduce
1. load up Kudo Jar
2. click on 'To' input
3. start typing a name

## Expected result
An autocomplete so I can assign kudos to a specific someone (as assigning kudos to a specific person _only_ works when selecting that person from the autocomplete)

## Actual result
Nothing happens. I do get an error in my console though, which seems to be related:

<img width="445" alt="screen shot 2017-01-30 at 12 05 32" src="https://cloud.githubusercontent.com/assets/1873829/22420877/c1e5ab44-e6e4-11e6-987b-8a702db44ba4.png">

## Additional info
* Browser: Firefox Developer Edition 52.0a2

**Comment by flarik** [comment]
Same goes for Safari Version 10.0.3 (12602.4.8)

<img width="1126" alt="screen shot 2017-02-08 at 08 29 17" src="https://cloud.githubusercontent.com/assets/194395/22727345/c182b214-edd8-11e6-8ffe-c7578ba87d14.png">
